// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

// Explicitly load .env.local
dotenv.config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
    //shadowDatabaseUrl: env('SHADOW_DATABASE_URL'),
  },
});
